### PR TITLE
提供首頁內文可以 include markdown 方式

### PR DESCRIPTION
**Pull request by shelling**

### CODE REVIEW

**Comment by clkao** [comment]
Is there any sample to show how this works?  I assume simply `require('./xxx.md')` ?

**Comment by yhsiang** [comment]
related #273

**Comment by yhsiang** [comment]
Example Code

```
import React, { Component } from "react";
import { getLocale } from "javascripts/locale";
import staff from './staffs.md';
import styles from './styles.css';

class StaffList extends Component {
  render() {
    return (
      <div className={styles.root}>
        <div
          className={styles.wrapper}
          dangerouslySetInnerHTML={{__html: staff }}
        />
      </div>
    );
  }
};

export default StaffList;
```

**Pull request merged**
